### ISSUE TITLE
Theme parsing error in gtk-dark.css

### ISSUE THREAD

**Issue by AtomToast** [Fausto-Korpsvart/Gruvbox-GTK-Theme#93]
Everytime I launch a gtk application from the terminal I get a gtk warning 

```
Gtk-WARNING **: 13:46:40.551: Theme parsing error: gtk-dark.css:6664:15: Junk at end of value for padding
```

Which leads to the offending rule

```css
dialog-host > floating-sheet > sheet > widget.response-area {
  padding: 6px !important;
}
```

I'm not sure if the `!important` is actually necessary for anything but removing it manually does at least resolve the warning
